# Набор тестов для non JWT эндпоинтов которые можно запустить
# в VSCode с помощью плагина  REST Client
# Найти можно по идентификатору: humao.rest-client


# Создаем продавца 1
POST http://localhost:8000/api/v1/nonjwt/sellers/ HTTP/1.1
content-type: application/json

{
    "first_name": "Martin",
    "second_name": "Iden",
    "email": "martiniden@gmail.com",
    "password": "test00"
}
###

# Создаем продавца 2
POST http://localhost:8000/api/v1/nonjwt/sellers/ HTTP/1.1
content-type: application/json

{
    "first_name": "Zen",
    "second_name": "Pythonovich",
    "email": "zenpythonovich@gmail.com",
    "password": "test00"
}

###

# Меняем продавца 1
PUT http://localhost:8000/api/v1/nonjwt/sellers/1 HTTP/1.1
content-type: application/json

{
    "first_name": "Martin",
    "second_name": "Idenza",
    "email": "martinidenza@gmail.com"
}

###

# Получаем список продавцoв
GET http://localhost:8000/api/v1/nonjwt/sellers/ HTTP/1.1

###

# Создаем книгу 1 для продавца 1 
POST http://localhost:8000/api/v1/nonjwt/books/ HTTP/1.1
content-type: application/json

{
    "seller_id": 1,
    "title": "Wrong Code",
    "author": "Robert Martin",
    "pages": 104,
    "year": 2007
}

###

# Создаем книгу 2 для продавца 1
POST http://localhost:8000/api/v1/nonjwt/books/ HTTP/1.1
content-type: application/json

{
    "seller_id": 1,
    "title": "Clean Code",
    "author": "Robert Martin",
    "pages": 104,
    "year": 2007
}

###

# Создаем книгу 1 для продавца 2
POST http://localhost:8000/api/v1/nonjwt/books/ HTTP/1.1
content-type: application/json

{
    "seller_id": 2,
    "title": "Do Did Done",
    "author": "Good Person",
    "pages": 78,
    "year": 2020
}

###

# Создаем книгу 2 для продавца 2
POST http://localhost:8000/api/v1/nonjwt/books/ HTTP/1.1
content-type: application/json

{
    "seller_id": 2,
    "title": "Rich Dad Poor Dad",
    "author": "Robert T. Kiyosaki & Sharon Lechter",
    "pages": 207,
    "year": 1997
}

###


# Получить информацию о продавце 1
GET http://localhost:8000/api/v1/nonjwt/sellers/1 HTTP/1.1

###

# Получить информацию о продавце 2
GET http://localhost:8000/api/v1/nonjwt/sellers/2 HTTP/1.1

###

# Меняем данные книги 1 для продавца 1
PUT http://localhost:8000/api/v1/nonjwt/books/1 HTTP/1.1
content-type: application/json

{
    "seller_id": 1,
    "title": "Clean Code",
    "author": "Robert Martin",
    "pages": 104,
    "year": 2007
}

###

# Меняем данные книги 1 для продавца 2
PUT http://localhost:8000/api/v1/nonjwt/books/3 HTTP/1.1
content-type: application/json

{
    "seller_id": 2,
    "title": "Do Did Done",
    "author": "Very Good Person",
    "pages": 99,
    "year": 2020,
    "id": 3
}

###

# Удаляем книгу 1 продавца 1
DELETE http://localhost:8000/api/v1/nonjwt/books/1 HTTP/1.1
content-type: application/json

###

# Удалим данные продавца 2
DELETE http://localhost:8000/api/v1/nonjwt/sellers/2 HTTP/1.1
content-type: application/json

###

# Получить список всех книг
GET  http://localhost:8000/api/v1/nonjwt/books/ HTTP/1.1

###


# Получить кнугу с id = 2
GET  http://localhost:8000/api/v1/nonjwt/books/2 HTTP/1.1

###